title: Edwin Moradian
tagline: Software Engineer
logo: /assets/img/old-school-pixel.jpg
description: Hi, I’m Edwin Moradian. Software engineer with a background in physics and 8 years of experience building distributed systems, AI-driven features, and full-stack applications. Currently focused on multi-agent systems and AI evaluation tooling. Feel free to explore my projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
