title: Edwin Moradian
logo: /assets/img/old-school-pixel.jpg
description: Hi, I’m Edwin Moradian — a full-stack software engineer with a background in physics and a focus on building reliable, scalable web applications. For the last 7 years, I’ve worked across the stack—from frontend interfaces to backend systems and infrastructure—collaborating with remote teams. Feel free to explore my recent work.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
